stages:
    - build
    
before_script:
    - 'dotnet restore'
    
variables:
    project: "Domain"
    test: "DomainTesting"

build_nuget:
    stage: build
    image:
        name: mcr.microsoft.com/dotnet/core/sdk:3.0.101-disco
    script:
        - 'dotnet msbuild InventorySystem.sln /t:Clean,ReBuild /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet pack "$project/$project.csproj" /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet nuget push'
    only:
        - master
