stages:
    - build
before_script:
    - 'nuget restore InventorySystem.sln'
build_nuget:
    stage: build
    image:
        name: mcr.microsoft.com/dotnet/core/sdk
    script:
        - 'dotnet msbuild InventorySystem.sln /t:Clean,ReBuild /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet pack "Domain/Domain.csproj" /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet nuget push'
    only:
        - master
