stages:
    - build
    
before_script:
    - 'dotnet restore'
    
variables:
    project: "Domain"
    test: "DomainTesting"

build_nuget:
    stage: build
    image:
        name: microsoft/dotnet:latest
    script:
        - 'dotnet msbuild InventorySystem.sln /t:Clean,ReBuild /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet pack "$project/$project.csproj" /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet nuget push'
    only:
        - master
