stages:
    - build
    
before_script:
    - 'dotnet restore'
    
variables:
    nugetPackage: "InventorySystem.Domain.DiegoBalmaceda.1.0.0.nupkg"

build_nuget:
    stage: build
    image:
        name: mcr.microsoft.com/dotnet/core/sdk:3.0.101-disco
    script:
        - 'dotnet msbuild InventorySystem.sln /t:Clean,ReBuild /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet nuget push /builds/xaesdesign/inventory-system/Domain/bin/Release/$nugetPackage -k oy2mmhfyiyqzw422cmpapauvdursg6ouzjpnhunmcuhody -s https://api.nuget.org/v3/index.json'
    only:
        - master
