stages:
    - deploy
before_script:
    - 'nuget restore InventorySystem.sln'
deploy_mysolution:
    stage: deploy
    image:
        name: crunchtime/dotnetcore-nuget-msbuild-docker
    script:
        - 'dotnet msbuild InventorySystem.sln /t:Clean,ReBuild /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet pack "Domain/Domain.csproj" /p:Configuration=Release;Platform="Any CPU"'
        - 'dotnet nuget push'
    only:
        - master
