drop table Costo
drop table Existencia
drop table LineaDocumento
drop table Documento
drop table Movimiento
drop table Localizacion
drop table Estante
drop table Pasillo
drop table Bodega
drop table Periodo
drop table Proveedor
drop table RepuestoCompatibilidad
drop table ModeloVehiculo
drop table Repuesto
drop table MarcaRepuesto
drop table SubCategoria
drop table Categoria
drop table TipoDocumento
